name: Build LaTeX document
on: [push]

permissions:
  contents: write
  pull-requests: write

env:
  REPOSITORY_MAIN_BRANCH: "master"
  MANIFEST_REPOSITORY: mosoriob/website 
  MANIFEST_REPOSITORY_BRANCH: master
  STATIC_REPOSITORY_PATH: static/pdf


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

  update:
    # This job the container running on k8s cluster
    needs: [build, security]
    name: "Deploy the app"
    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - name: Check out k8s manifests
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          repository: ${{ env.MANIFEST_REPOSITORY }}
          ref: ${{ env.MANIFEST_REPOSITORY_BRANCH }}
          persist-credentials: true

      - name: Update Kubernetes resources neuro
        if: github.event_name != 'pull_request'
        run: |
          cd ${{ env.NEURO_MANIFEST_REPOSITORY_PATH }}
          kustomize edit set image ${{ env.KUSTOMIZE_IMAGE_NAME }}=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME}}:${{ needs.build.outputs.docker_tag }}
          cat kustomization.yaml

      - name: Commit files
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Updated resume"
          
      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ env.MANIFEST_REPOSITORY_BRANCH }}
          repository: ${{ env.MANIFEST_REPOSITORY }}